# Generated by Django 3.2 on 2021-04-17 11:09

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=300, verbose_name='Username')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Registered')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('activation', 'Activation'), ('recovery', 'Recovery'), ('login', 'Login')], max_length=30, verbose_name='For')),
                ('code', models.CharField(default=accounts.models.generate_random_code, max_length=10, verbose_name='Code')),
                ('security_token', models.CharField(default=accounts.models.generate_security_token, max_length=45, verbose_name='Security token')),
                ('expires', models.DateTimeField(default=accounts.models.generate_expiration_date, verbose_name='Expiration date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Auth code',
                'verbose_name_plural': 'Auth codes',
                'unique_together': {('user', 'purpose', 'code')},
            },
        ),
    ]
