# Generated by Django 3.2 on 2021-04-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
